name: Build project

on: 
  push:   
    branches: 
      - main
      - master

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          # Add all the target platforms that need to built here
          - StandaloneWindows64 # Build a Windows 64-bit standalone. (Mono)
          - WebGL # WebGL.
    steps:
      
      # Checkout 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      
      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}


      # Build
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          allowDirtyBuild: true
    

      # Upload Butler
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.targetPlatform }}
          ITCH_GAME: YOUR_GAME_NAME
          ITCH_USER: YOU_USER_NAME
          PACKAGE: build/${{ matrix.targetPlatform }}
